# Generated by Django 4.0.4 on 2022-05-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etykieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('kolor', models.CharField(max_length=255)),
                ('priorytet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kolumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_stworzenia', models.DateTimeField(auto_now_add=True)),
                ('czy_zrobione', models.BooleanField(default=False)),
                ('czy_wazne', models.BooleanField(default=False)),
                ('zawartosc', models.TextField()),
                ('data_rozpoczecia', models.DateTimeField(blank=True, null=True)),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True)),
                ('kolumna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.kolumna')),
            ],
        ),
        migrations.CreateModel(
            name='RolaWAplikacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tablica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('czy_zautomatyzowane', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('zdjecie', models.ImageField(blank=True, upload_to='profile_pics')),
                ('rola_w_aplikacji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.rolawaplikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='images')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.notatka')),
            ],
        ),
        migrations.CreateModel(
            name='UzytkownikNotatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.notatka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='TablicaUzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola_w_tablicy', models.CharField(max_length=255)),
                ('tablica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.tablica')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='TablicaEtykieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.etykieta')),
                ('tablica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.tablica')),
            ],
        ),
        migrations.CreateModel(
            name='NotatkaEtykieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.etykieta')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.notatka')),
            ],
        ),
        migrations.AddField(
            model_name='notatka',
            name='stworzone_przez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.uzytkownik'),
        ),
        migrations.AddField(
            model_name='kolumna',
            name='tablica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.tablica'),
        ),
    ]
