# Generated by Django 4.0.4 on 2022-05-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RESTApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZdjecieUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='zdjecia/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablicaetykieta',
            name='etykieta',
        ),
        migrations.RemoveField(
            model_name='tablicaetykieta',
            name='tablica',
        ),
        migrations.RemoveField(
            model_name='tablicauzytkownik',
            name='tablica',
        ),
        migrations.RemoveField(
            model_name='tablicauzytkownik',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='rola_w_aplikacji',
        ),
        migrations.RemoveField(
            model_name='uzytkowniknotatka',
            name='notatka',
        ),
        migrations.RemoveField(
            model_name='uzytkowniknotatka',
            name='uzytkownik',
        ),
        migrations.AddField(
            model_name='notatka',
            name='etykieta',
            field=models.ManyToManyField(to='RESTApi.etykieta'),
        ),
        migrations.AddField(
            model_name='notatka',
            name='przypisany_uzytkownik',
            field=models.ManyToManyField(related_name='przypisany_uzytkownik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablica',
            name='uzytkownicy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notatka',
            name='stworzone_przez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotatkaEtykieta',
        ),
        migrations.DeleteModel(
            name='RolaWAplikacji',
        ),
        migrations.DeleteModel(
            name='TablicaEtykieta',
        ),
        migrations.DeleteModel(
            name='TablicaUzytkownik',
        ),
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
        migrations.DeleteModel(
            name='UzytkownikNotatka',
        ),
    ]
