# Generated by Django 4.0.4 on 2022-06-16 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RESTApi', '0002_zdjecieuzytkownika_remove_tablicaetykieta_etykieta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatka',
            name='przypisany_uzytkownik',
        ),
        migrations.CreateModel(
            name='UzytkownikNotatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.notatka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
