# Generated by Django 4.0.4 on 2022-06-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0003_remove_notatka_przypisany_uzytkownik_and_more'),
        ('RESTApi', '0003_remove_tablica_uzytkownicy_tablicauzytkownik'),
    ]

    operations = [
    ]
