# Generated by Django 4.0.4 on 2022-05-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0003_alter_uzytkownik_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='user',
        ),
    ]
