# Generated by Django 4.0.4 on 2022-06-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0004_merge_20220616_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatka',
            name='etykieta',
        ),
        migrations.CreateModel(
            name='TablicaEtykieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.etykieta')),
                ('tablica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.tablica')),
            ],
        ),
        migrations.CreateModel(
            name='NotatkaEtykieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.etykieta')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.notatka')),
            ],
        ),
    ]
