# Generated by Django 4.0.4 on 2022-05-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0002_zdjecieuzytkownika_remove_tablicaetykieta_etykieta_and_more'),
        ('RESTApi', '0004_remove_uzytkownik_user'),
    ]

    operations = [
    ]
