# Generated by Django 4.0.4 on 2022-05-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0005_merge_20220524_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolaWAplikacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('zdjecie', models.ImageField(blank=True, upload_to='profile_pics')),
                ('rola_w_aplikacji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.rolawaplikacji')),
            ],
        ),
        migrations.CreateModel(
            name='TablicaUzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola_w_tablicy', models.CharField(max_length=255)),
                ('tablica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.tablica')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTApi.uzytkownik')),
            ],
        ),
    ]
