# Generated by Django 4.0.4 on 2022-05-26 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RESTApi', '0006_rolawaplikacji_uzytkownik_tablicauzytkownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablicauzytkownik',
            name='uzytkownik',
        ),
        migrations.AddField(
            model_name='tablicauzytkownik',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
    ]
