# Generated by Django 4.0.4 on 2022-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTApi', '0007_remove_tablicauzytkownik_uzytkownik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablica',
            name='uzytkownicy',
        ),
    ]
